import {
  faBoxOpen,
  faHome,
  faCompass,
  faCreditCard,
  faGem,
  faBox,
  faArrowRight,
  faPlus,
  faLayerGroup,
  faEye,
  faEyeSlash,
  faExternalLinkAlt,
  faStickyNote,
  faCloud,
  faStar,
  faUser,
  faUpload,
  faTrash,
  faUserPlus,
  faGift,
  faCode,
  faSave,
  faLock,
  faFolderOpen,
  faGreaterThan,
  faExclamationTriangle,
  faCheckCircle,
  faUserCog,
  faTag,
  faInfoCircle,
  faDownload,
  faEnvelope,
  faAward,
  faBolt,
  faChevronRight,
  faPlusCircle,
  faBell,
  faEnvelopeOpen,
  faTachometerAlt,
  faUsers,
  faChartLine,
  faTools,
  faBullhorn,
  faGifts,
  faMoneyBill,
  faCog,
  faSlidersH,
  faFilter,
  faArrowUp,
  faArrowDown,
  faSyncAlt,
  faSignOutAlt,
  faBan,
  faUserCheck,
  faPlay,
  faPause,
  faBars,
  faCommentAlt,
  faBook,
} from "@fortawesome/free-solid-svg-icons";

import {
  faFigma,
  faSlack,
  faGithub,
  faTrello,
  faDiscord,
  faGoogleDrive,
  faXTwitter,
  faFacebookF,
  faLinkedinIn,
  faWhatsapp,
  faInstagram,
  faTiktok,
} from "@fortawesome/free-brands-svg-icons";

import { faCalendar } from "@fortawesome/free-regular-svg-icons";
import { IconDefinition } from "@fortawesome/fontawesome-svg-core";

export const Icons = {
  boxOpen: faBoxOpen as IconDefinition,
  layerGroup: faLayerGroup as IconDefinition,
  Home: faHome as IconDefinition,
  Compass: faCompass as IconDefinition,
  CreditCard: faCreditCard as IconDefinition,
  Gem: faGem as IconDefinition,
  Box: faBox as IconDefinition,
  ArrowRight: faArrowRight as IconDefinition,
  Plus: faPlus as IconDefinition,
  EyeOpen: faEye as IconDefinition,
  EyeClose: faEyeSlash as IconDefinition,
  Figma: faFigma as IconDefinition,
  ExternalLink: faExternalLinkAlt as IconDefinition,
  Slack: faSlack as IconDefinition,
  Notion: faStickyNote as IconDefinition,
  Github: faGithub as IconDefinition,
  Trello: faTrello as IconDefinition,
  Dropbox: faCloud as IconDefinition,
  Star: faStar as IconDefinition,
  Discord: faDiscord as IconDefinition,
  VSCode: faCode as IconDefinition,
  GoogleDrive: faGoogleDrive as IconDefinition,
  UserPlus: faUserPlus as IconDefinition,
  Upload: faUpload as IconDefinition,
  Trash: faTrash as IconDefinition,
  User: faUser as IconDefinition,
  Save: faSave as IconDefinition,
  Lock: faLock as IconDefinition,
  Greater: faGreaterThan as IconDefinition,
  Warning: faExclamationTriangle as IconDefinition,
  FolderOpen: faFolderOpen as IconDefinition,
  Settings: faUserCog as IconDefinition,
  Tag: faTag as IconDefinition,
  Info: faInfoCircle as IconDefinition,
  Message: faEnvelope as IconDefinition,
  Facebook: faFacebookF as IconDefinition,
  X: faXTwitter as IconDefinition,
  Linkedin: faLinkedinIn as IconDefinition,
  Whatsapp: faWhatsapp as IconDefinition,
  Award: faAward as IconDefinition,
  Calender: faCalendar as IconDefinition,
  Flash: faBolt as IconDefinition,
  Right: faChevronRight as IconDefinition,
  Instagram: faInstagram as IconDefinition,
  TikTok: faTiktok as IconDefinition,
  PlusCircle: faPlusCircle as IconDefinition,
  Bell: faBell as IconDefinition,
  openMessage: faEnvelopeOpen as IconDefinition,
  CheckCircle: faCheckCircle as IconDefinition,
  Gift: faGift as IconDefinition,
  Tachometer: faTachometerAlt as IconDefinition,
  Users: faUsers as IconDefinition,
  Chart: faChartLine as IconDefinition,
  Tools: faTools as IconDefinition,
  BullHorn: faBullhorn as IconDefinition,
  Gifts: faGifts as IconDefinition,
  MoneyBill: faMoneyBill as IconDefinition,
  Cog: faCog as IconDefinition,
  Slider: faSlidersH as IconDefinition,
  Filter: faFilter as IconDefinition,
  Download: faDownload as IconDefinition,
  ArrowUp: faArrowUp as IconDefinition,
  ArrowDown: faArrowDown as IconDefinition,
  Sync: faSyncAlt as IconDefinition,
  Signout: faSignOutAlt as IconDefinition,
  Ban: faBan as IconDefinition,
  Unban: faUserCheck as IconDefinition,
  Menu: faBars as IconDefinition,
  Play: faPlay as IconDefinition,
  Pause: faPause as IconDefinition,
  Chat: faCommentAlt as IconDefinition,
  Blog : faBook as IconDefinition
};
